import * as authAPI from './auth'
import * as dailyReport from './report'
import * as fixData from './fixData'
import * as variableData from './variableData'
import * as license from './license'
import * as examScope from './examScope'
import * as operators from './operators'
import * as examOrganizer from './examOrganizer'
import * as scopeUser from './scopeUser'
import * as booklet from './booklet'
export { authAPI, dailyReport, fixData, variableData, license, examScope, operators, examOrganizer, scopeUser,booklet }
